# Generated by Django 3.0.4 on 2020-03-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='u2_image',
            field=models.ImageField(upload_to='../user2/test_img/'),
        ),
    ]
