# Generated by Django 3.0.4 on 2020-03-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user2', '0002_auto_20200308_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='u2_image',
            field=models.ImageField(upload_to='test_img/'),
        ),
    ]
