# Generated by Django 3.0.2 on 2020-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='u_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
