# Generated by Django 3.0.4 on 2020-03-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0002_reports_u_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='u_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='address',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='mob_nu',
        ),
        migrations.AlterField(
            model_name='reports',
            name='u_image',
            field=models.ImageField(upload_to='images/title.jpg'),
        ),
    ]
